sudo: false

os:
  - linux
  - osx

language: rust
rust: nightly

cache: cargo

script:
  - rustup toolchain install nightly
  - rustup target install wasm32-unknown-unknown
  - cargo +nightly build --verbose --all --target wasm32-unknown-unknown
  - cargo +nightly test --verbose --all --target wasm32-unknown-unknown

notifications:
  email: cassiokirch@gmail.com
  on_success: always
